#!/usr/bin/env bash
# installs nginx, and some other configs on the server
sudo -y apt-get update
sudo apt-get install nginx -y
echo "Hello World!" > /var/www/html/index.html
sudo service nginx start
