#!/usr/bin/env bash
# installs nginx, and some other configs on the server
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
sudo service nginx start
