#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01

apt update -y
apt upgrade -y

apt-get install --no-install-recommends software-properties-common -y
add-apt-repository ppa:vbernat/haproxy-2.0 -y

apt-get install haproxy=2.0.\* -y

frontend="frontend http-in\n\tbind *:80\n\tmode http\n\tdefault_backend servers"
backend="backend servers\n\tbalance roundrobin\n\tmode http\n\tserver 221351-web-01 34.229.137.157:80 check\n\tserver 221351-web-02 100.26.249.157:80 check\n"

echo -e "$frontend\n$backend" | sudo tee -a /etc/haproxy/haproxy.cfg

service haproxy restart
