#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01

apt update -y
apt upgrade -y

apt-get install --no-install-recommends software-properties-common -y
add-apt-repository ppa:vbernat/haproxy-2.0 -y

apt-get install haproxy=2.0.\* -y

