#!/usr/bin/env bash
# displays 'To infinity and beyond' indefinitely
i=0
touch /var/run/myscript.pid
sudo echo $$ > /var/run/myscript.pid
trap 'echo "I hate the kill command" ; rm /var/run/myscript.pid ; exit' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm /var/run/myscript.pid ; exit' SIGQUIT
while [ $i -eq 0 ]
do
	echo "To infinity and beyond"
	sleep 2
done
