#!/usr/bin/env bash
# list lines of the processes list containing bash
# shellcheck disable=SC2009
# shellcheck disable=SC2086
pid=`ps -aux | grep ./4-to_infinity_and_beyond | awk '{print $2)`
kill $pid
