#!/usr/bin/env bash
# change some some config in the /etc/host file

old="^127.0.0.1( |\t){1,10}localhost( |\t){0,10}$"
new="127.0.0.2	localhost"

sed -i "s/$old/$new/g" /etc/hosts

echo -e "8.8.8.8\tfacebook.com" >> /etc/hosts
