#!/usr/bin/env bash
# debug docker
docker exec -ti holbertonschool/265-0 /bin/bash
sudo apt update -y
sudo apt install apache2 -y
echo "Hello Holberton" | sudo tee /var/www/html
sudo service apache2 restart
