#!/usr/bin/env bash
# change the owner of the nginx process
sudo chown -R  nginx:nginx /etc/nginx/conf.d
sudo chmod 644 /etc/nginx/nginx.conf
sudo touch /var/run/nginx.pid
sudo chown  nginx:nginx /var/run/nginx.pid
sudo sed -i 's/listen 80/listen 8080/' /etc/nginx/sites-enabled/default
sudo sed -i 's/listen \[::\]:80/listen [::]:8080/' /etc/nginx/sites-enabled/default
sudo nginx -t
sudo -u nginx  nginx